<?php
$companyId = user()['company_id'];
$companyStmt = db()->prepare('SELECT * FROM companies WHERE id = ?'); $companyStmt->execute([$companyId]); $company = $companyStmt->fetch();
$employeeCount = db()->prepare("SELECT COUNT(*) FROM employees WHERE company_id=? AND status='active'"); $employeeCount->execute([$companyId]);
$todaySql = env('DB_DRIVER', 'sqlite') === 'mysql'
    ? 'SELECT COUNT(*) FROM punches WHERE company_id=? AND DATE(punched_at)=CURDATE()'
    : "SELECT COUNT(*) FROM punches WHERE company_id=? AND date(punched_at)=date('now','localtime')";
$todayPunches = db()->prepare($todaySql); $todayPunches->execute([$companyId]);
$employees = db()->prepare('SELECT * FROM employees WHERE company_id=? ORDER BY name'); $employees->execute([$companyId]); $employeeRows = $employees->fetchAll();
$punches = db()->prepare('SELECT p.*,e.name,e.registration,e.department FROM punches p JOIN employees e ON e.id=p.employee_id WHERE p.company_id=? ORDER BY p.punched_at DESC LIMIT 40'); $punches->execute([$companyId]); $punchRows = $punches->fetchAll();
$scheduleStmt=db()->prepare('SELECT * FROM schedules WHERE company_id=? AND active=1 ORDER BY name');$scheduleStmt->execute([$companyId]);$scheduleRows=$scheduleStmt->fetchAll();
$settingsStmt=db()->prepare('SELECT * FROM company_settings WHERE company_id=?');$settingsStmt->execute([$companyId]);$settings=$settingsStmt->fetch()?:['daily_tolerance_minutes'=>10,'overtime_weekday_percent'=>50,'overtime_holiday_percent'=>100,'night_additional_percent'=>20,'night_hour_minutes'=>52,'closing_day'=>25];
$adjustmentStmt=db()->prepare("SELECT a.*,e.name FROM adjustments a JOIN employees e ON e.id=a.employee_id WHERE a.company_id=? AND a.status='pending' ORDER BY a.work_date DESC");$adjustmentStmt->execute([$companyId]);$pendingAdjustments=$adjustmentStmt->fetchAll();
$reportFrom=$_GET['from']??date('Y-m-01');$reportTo=$_GET['to']??date('Y-m-d');
$summaryStmt=db()->prepare('SELECT e.id,e.registration,e.name,COALESCE(SUM(d.worked_minutes),0) worked,COALESCE(SUM(d.expected_minutes),0) expected,COALESCE(SUM(d.overtime_minutes),0) overtime,COALESCE(SUM(d.delay_minutes),0) delays,COALESCE(SUM(d.night_minutes),0) night FROM employees e LEFT JOIN daily_calculations d ON d.employee_id=e.id AND d.company_id=e.company_id AND d.work_date BETWEEN ? AND ? WHERE e.company_id=? GROUP BY e.id,e.registration,e.name ORDER BY e.name');$summaryStmt->execute([$reportFrom,$reportTo,$companyId]);$reportSummary=$summaryStmt->fetchAll();
$monthFrom=date('Y-m-01');$monthTo=date('Y-m-d');
$monthStmt=db()->prepare('SELECT COALESCE(SUM(worked_minutes),0) worked,COALESCE(SUM(expected_minutes),0) expected,COALESCE(SUM(overtime_minutes),0) overtime,COALESCE(SUM(delay_minutes),0) delays FROM daily_calculations WHERE company_id=? AND work_date BETWEEN ? AND ?');$monthStmt->execute([$companyId,$monthFrom,$monthTo]);$monthTotals=$monthStmt->fetch();
$pendingCount=count($pendingAdjustments);$completion=(int)$monthTotals['expected']>0?min(100,(int)round(((int)$monthTotals['worked']/(int)$monthTotals['expected'])*100)):0;
$flash = $_SESSION['flash'] ?? null; unset($_SESSION['flash']);
$titles = ['dashboard'=>'Visão geral','employees'=>'Colaboradores','punches'=>'Marcações','treatment'=>'Tratamento de ponto','reports'=>'Relatórios','schedules'=>'Jornadas e escalas','companies'=>'Empresas','users'=>'Usuários e permissões','audit'=>'Auditoria','settings'=>'Configurações','404'=>'Página não encontrada'];
$nav = [['dashboard','grade','Visão geral'],['employees','users','Colaboradores'],['schedules','clock','Jornadas e escalas'],['punches','fingerprint','Marcações'],['treatment','wand','Tratamento'],['reports','file','Relatórios'],['companies','building','Empresas'],['users','users','Usuários'],['audit','shield','Auditoria'],['settings','settings','Configurações']];
function icon(string $name): string { $icons=['grade'=>'▦','users'=>'♙','clock'=>'◷','fingerprint'=>'◎','wand'=>'✦','file'=>'▤','building'=>'▥','shield'=>'◇','settings'=>'⚙']; return $icons[$name] ?? '•'; }
?>
<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= e($titles[$page]) ?> • Ponto Certo</title><link rel="stylesheet" href="/assets/app.css"><link rel="icon" href="/favicon.svg" type="image/svg+xml"></head>
<body><div class="app-shell">
<aside class="sidebar" id="sidebar">
  <a class="logo" href="/dashboard"><span class="brand-mark small">PC</span><span>Ponto <b>Certo</b></span></a>
  <div class="company-picker"><small>ORGANIZAÇÃO</small><strong><?= e($company['name']) ?></strong><span><?= e($company['document']) ?></span></div>
  <nav><?php foreach($nav as [$href,$ico,$label]): ?><a href="/<?= $href ?>" class="<?= $page===$href?'active':'' ?>"><span><?= icon($ico) ?></span><?= $label ?></a><?php endforeach; ?></nav>
  <div class="sidebar-foot"><div class="avatar">AN</div><div><strong><?= e(user()['name']) ?></strong><span><?= e(strtoupper(user()['role'])) ?></span></div><a href="/logout" title="Sair">↗</a></div>
</aside>
<main class="main">
  <header class="topbar"><button class="menu-button" id="menuButton" aria-label="Abrir menu">☰</button><div><p class="eyebrow">SEXTA-FEIRA, <?= date('d/m/Y') ?></p><h1><?= e($titles[$page]) ?></h1></div><div class="top-actions"><button class="icon-button" aria-label="Notificações">♢<span></span></button><a class="button primary" href="/punches">+ Importar marcações</a></div></header>
  <section class="content">
  <?php if ($flash): ?><div class="alert success"><?= e($flash) ?></div><?php endif; ?>
  <?php if ($page==='dashboard'): ?>
    <div class="period-bar"><div><span>Período atual</span><strong>01/<?= date('m/Y') ?> — <?= date('d/m/Y') ?></strong></div><a class="button ghost" href="/reports">Alterar período</a></div>
    <div class="stats">
      <article class="stat"><span class="stat-icon blue">♙</span><div><small>COLABORADORES ATIVOS</small><strong><?= (int)$employeeCount->fetchColumn() ?></strong><em>Cadastro atualizado</em></div></article>
      <article class="stat"><span class="stat-icon cyan">◎</span><div><small>MARCAÇÕES HOJE</small><strong><?= (int)$todayPunches->fetchColumn() ?></strong><em>Recebidas pelo agente</em></div></article>
      <article class="stat"><span class="stat-icon amber">!</span><div><small>INCONSISTÊNCIAS</small><strong><?= $pendingCount ?></strong><em>Precisam de análise</em></div></article>
      <article class="stat"><span class="stat-icon green">✓</span><div><small>APURAÇÃO</small><strong><?= $completion ?>%</strong><em><?= date('m/Y') ?></em></div></article>
    </div>
    <div class="dashboard-grid">
      <article class="panel"><div class="panel-head"><div><h2>Ocorrências que exigem atenção</h2><p>Prioridades do período atual</p></div><a href="/treatment">Ver todas</a></div>
        <?php foreach(array_slice($pendingAdjustments,0,3) as $a): ?><div class="issue"><span class="issue-icon danger">!</span><div><strong><?= e($a['kind']) ?></strong><p><?= e($a['name']) ?> • <?= e(date('d/m/Y',strtotime($a['work_date']))) ?></p></div><span class="badge danger">Pendente</span></div><?php endforeach; ?>
        <?php if(!$pendingAdjustments): ?><div class="empty-state"><p>Nenhuma ocorrência pendente.</p></div><?php endif; ?>
      </article>
      <article class="panel"><div class="panel-head"><div><h2>Resumo da jornada</h2><p>Horas apuradas no mês</p></div></div>
        <div class="hours-total"><span>Horas previstas</span><strong><?= ReportExporter::hours($monthTotals['expected']) ?></strong></div>
        <div class="progress"><i style="width:<?= $completion ?>%"></i></div>
        <div class="hours-grid"><div><span>Trabalhadas</span><b><?= ReportExporter::hours($monthTotals['worked']) ?></b></div><div><span>Extras</span><b class="positive">+<?= ReportExporter::hours($monthTotals['overtime']) ?></b></div><div><span>Atrasos</span><b class="negative">−<?= ReportExporter::hours($monthTotals['delays']) ?></b></div><div><span>Banco</span><b><?= ReportExporter::signed((int)$monthTotals['worked']-(int)$monthTotals['expected']) ?></b></div></div>
      </article>
    </div>
    <article class="panel"><div class="panel-head"><div><h2>Últimas marcações</h2><p>Sincronização em tempo real com o agente comunicador</p></div><span class="live"><i></i> Agente conectado</span></div><?php render_punch_table(array_slice($punchRows,0,6)); ?></article>
  <?php elseif ($page==='employees'): ?>
    <div class="page-actions"><div><h2>Equipe cadastrada</h2><p><?= count($employeeRows) ?> colaboradores encontrados</p></div><button class="button primary" data-modal="employeeModal">+ Novo colaborador</button></div>
    <article class="panel table-panel"><div class="filters"><input id="employeeSearch" placeholder="Pesquisar nome, matrícula ou setor"><select id="employeeStatus"><option value="">Todos os status</option><option value="active">Ativos</option><option value="leave">Afastados</option><option value="vacation">Férias</option><option value="inactive">Inativos</option></select></div><div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Matrícula</th><th>Setor / cargo</th><th>Jornada</th><th>Status</th><th>Ações</th></tr></thead><tbody id="employeeRows"><?php foreach($employeeRows as $row): ?><tr data-status="<?= e($row['status']) ?>"><td><strong><?= e($row['name']) ?></strong><small><?= e($row['cpf']) ?></small></td><td><?= e($row['registration']) ?></td><td><?= e($row['department']) ?><small><?= e($row['job_title']) ?></small></td><td><?= e($row['schedule_name']) ?></td><td><span class="badge <?= $row['status']==='active'?'success':'warning' ?>"><?= e(['active'=>'Ativo','inactive'=>'Inativo','vacation'=>'Férias','leave'=>'Afastado'][$row['status']]??$row['status']) ?></span></td><td><button class="button ghost" data-modal="employeeEdit<?= (int)$row['id'] ?>">Editar</button></td></tr><?php endforeach; ?></tbody></table></div></article>
    <?php foreach($employeeRows as $row): ?><dialog id="employeeEdit<?= (int)$row['id'] ?>"><form method="post" action="/employees/update"><div class="modal-head"><h2>Editar colaborador</h2><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="employee_id" value="<?= (int)$row['id'] ?>"><div class="form-grid"><label class="span-2">Nome<input name="name" value="<?= e($row['name']) ?>" required></label><label>CPF<input name="cpf" value="<?= e($row['cpf']) ?>"></label><label>Setor<input name="department" value="<?= e($row['department']) ?>" required></label><label>Cargo<input name="job_title" value="<?= e($row['job_title']) ?>" required></label><label>Status<select name="status"><?php foreach(['active'=>'Ativo','inactive'=>'Inativo','vacation'=>'Férias','leave'=>'Afastado'] as $value=>$label): ?><option value="<?= $value ?>" <?= $row['status']===$value?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></label></div><div class="modal-actions"><button class="button primary">Salvar alterações</button></div></form></dialog><?php endforeach; ?>
    <dialog id="employeeModal"><form method="post" action="/employees/new"><div class="modal-head"><div><p class="eyebrow">CADASTRO</p><h2>Novo colaborador</h2></div><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><div class="form-grid"><label class="span-2">Nome completo<input name="name" required></label><label>Matrícula<input name="registration" required></label><label>CPF<input name="cpf" placeholder="000.000.000-00"></label><label>Setor<input name="department" required></label><label>Cargo<input name="job_title" required></label><label class="span-2">Jornada<input name="schedule_name" value="Seg–Sex • 08:00–17:00" required></label></div><div class="modal-actions"><button type="button" class="button ghost close-modal">Cancelar</button><button class="button primary">Salvar colaborador</button></div></form></dialog>
    <article class="panel detail-card"><h2>Atribuir jornada</h2><p class="muted">A alteração mantém o histórico das jornadas anteriores.</p><form method="post" action="/employees/assign-schedule"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><div class="form-grid"><label>Colaborador<select name="employee_id" required><?php foreach($employeeRows as $row): ?><option value="<?= (int)$row['id'] ?>"><?= e($row['name']) ?></option><?php endforeach; ?></select></label><label>Jornada<select name="schedule_id" required><?php foreach($scheduleRows as $s): ?><option value="<?= (int)$s['id'] ?>"><?= e($s['name']) ?></option><?php endforeach; ?></select></label><label>Início da vigência<input type="date" name="starts_on" value="<?= date('Y-m-d') ?>" required></label></div><button class="button primary">Atribuir jornada</button></form></article>
  <?php elseif ($page==='punches'): ?>
    <div class="page-actions"><div><h2>Marcações recebidas</h2><p>Originais preservados e identificados por hash</p></div><div><button class="button ghost" data-modal="manualPunchModal">+ Marcação manual</button> <button class="button primary" data-modal="afdModal">Importar AFD</button></div></div><article class="panel table-panel"><?php render_punch_table($punchRows); ?></article>
    <dialog id="manualPunchModal"><form method="post" action="/punches/manual"><div class="modal-head"><h2>Marcação manual</h2><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><label>Colaborador<select name="employee_id" required><?php foreach($employeeRows as $row): ?><option value="<?= (int)$row['id'] ?>"><?= e($row['name']) ?></option><?php endforeach; ?></select></label><label>Data e hora<input type="datetime-local" name="punched_at" value="<?= date('Y-m-d\\TH:i') ?>" required></label><label>Justificativa<textarea name="reason" rows="3" required></textarea></label><div class="modal-actions"><button class="button primary">Registrar marcação</button></div></form></dialog>
    <dialog id="afdModal"><form method="post" action="/punches/import" enctype="multipart/form-data"><div class="modal-head"><div><p class="eyebrow">RELÓGIO DE PONTO</p><h2>Importar marcações</h2></div><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><label>Arquivo AFD ou CSV<input type="file" name="afd" accept=".txt,.afd,.csv,text/plain,text/csv" required></label><p class="muted">Limite de 10 MB. Marcações duplicadas serão ignoradas.</p><div class="modal-actions"><button type="button" class="button ghost close-modal">Cancelar</button><button class="button primary">Iniciar importação</button></div></form></dialog>
  <?php elseif ($page==='treatment'): ?>
    <form id="processPeriodForm" method="post" action="/treatment/process" hidden><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="from" value="<?= date('Y-m-01') ?>"><input type="hidden" name="to" value="<?= date('Y-m-d') ?>"></form>
    <div class="page-actions"><div><h2>Fila de tratamento</h2><p>Analise ocorrências antes do fechamento</p></div><button class="button primary">Processar período</button></div>
    <article class="panel detail-card"><h2>Registrar tratamento</h2><form method="post" action="/treatment/save"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><div class="form-grid"><label>Colaborador<select name="employee_id"><?php foreach($employeeRows as $row): ?><option value="<?= (int)$row['id'] ?>"><?= e($row['name']) ?></option><?php endforeach; ?></select></label><label>Data<input type="date" name="work_date" value="<?= date('Y-m-d') ?>"></label><label>Ocorrência<select name="kind"><option value="missing_punch">Marcação ausente</option><option value="delay">Atraso</option><option value="absence">Falta</option><option value="medical">Atestado</option><option value="compensation">Compensação</option></select></label><label>Horário ajustado<input type="time" name="adjusted_value"></label><label class="span-2">Justificativa<textarea name="reason" rows="3" required></textarea></label></div><button class="button primary">Enviar para aprovação</button></form></article>
    <?php if($pendingAdjustments): ?><article class="panel table-panel"><div class="panel-head"><div><h2>Tratamentos aguardando decisão</h2><p><?= count($pendingAdjustments) ?> pendências</p></div></div><div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Data</th><th>Tipo</th><th>Justificativa</th><th>Decisão</th></tr></thead><tbody><?php foreach($pendingAdjustments as $a): ?><tr><td><?= e($a['name']) ?></td><td><?= e(date('d/m/Y',strtotime($a['work_date']))) ?></td><td><?= e($a['kind']) ?></td><td><?= e($a['reason']) ?></td><td><form method="post" action="/treatment/approve"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="adjustment_id" value="<?= (int)$a['id'] ?>"><button class="button primary" name="decision" value="approve">Aprovar</button> <button class="button ghost" name="decision" value="reject">Rejeitar</button></form></td></tr><?php endforeach; ?></tbody></table></div></article><?php endif; ?>
  <?php elseif ($page==='reports'): ?>
    <article class="panel detail-card"><h2>Período dos relatórios</h2><form method="get" action="/reports"><div class="form-grid"><label>Início<input type="date" name="from" value="<?= e($reportFrom) ?>" required></label><label>Fim<input type="date" name="to" value="<?= e($reportTo) ?>" required></label></div><button class="button primary">Aplicar período</button></form></article>
    <article class="panel table-panel"><div class="panel-head"><div><h2>Resumo por colaborador</h2><p>Horas calculadas entre <?= e(date('d/m/Y',strtotime($reportFrom))) ?> e <?= e(date('d/m/Y',strtotime($reportTo))) ?></p></div><a class="button ghost" href="/reports/payroll.csv?from=<?= e($reportFrom) ?>&to=<?= e($reportTo) ?>">Baixar CSV</a></div><div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Trabalhadas</th><th>Previstas</th><th>Extras</th><th>Atrasos</th><th>Noturnas</th><th>Saldo</th><th>Espelho</th></tr></thead><tbody><?php foreach($reportSummary as $r): ?><tr><td><strong><?= e($r['name']) ?></strong><small><?= e($r['registration']) ?></small></td><td><?= ReportExporter::hours($r['worked']) ?></td><td><?= ReportExporter::hours($r['expected']) ?></td><td><?= ReportExporter::hours($r['overtime']) ?></td><td><?= ReportExporter::hours($r['delays']) ?></td><td><?= ReportExporter::hours($r['night']) ?></td><td><?= ReportExporter::signed((int)$r['worked']-(int)$r['expected']) ?></td><td><a class="button ghost" href="/timecard?employee_id=<?= (int)$r['id'] ?>&from=<?= e($reportFrom) ?>&to=<?= e($reportTo) ?>">Abrir</a></td></tr><?php endforeach; ?></tbody></table></div></article>
    <div class="report-grid"><article class="report-card"><span>▤</span><div><h2>Arquivo AEJ</h2><p>Exportação das marcações para conferência.</p></div><a class="button ghost" href="/reports/aej.txt?from=<?= e($reportFrom) ?>&to=<?= e($reportTo) ?>">Baixar</a></article><article class="report-card"><span>◇</span><div><h2>Auditoria</h2><p>Ajustes, justificativas e responsáveis.</p></div><a class="button ghost" href="/audit">Abrir</a></article></div>
    <div class="settings-grid"><article class="panel"><h2>Resumo para folha</h2><p class="muted">Exporta horas trabalhadas, previstas, extras, atrasos, noturnas e saldo.</p><a class="button primary" href="/reports/payroll.csv?from=<?= date('Y-m-01') ?>&to=<?= date('Y-m-d') ?>">Baixar CSV</a></article><article class="panel"><h2>Fechar período</h2><p class="muted">Após o fechamento, tratamentos ficam bloqueados.</p><form method="post" action="/period/close"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><label>Início<input type="date" name="from" value="<?= date('Y-m-01') ?>" required></label><label>Fim<input type="date" name="to" value="<?= date('Y-m-d') ?>" required></label><button class="button primary">Fechar período</button></form></article></div>
  <?php elseif ($page==='schedules'): ?>
    <div class="page-actions"><div><h2>Modelos de jornada</h2><p><?= count($scheduleRows) ?> jornadas configuradas</p></div><button class="button primary" data-modal="scheduleModal">+ Nova jornada</button></div><div class="schedule-grid"><?php foreach($scheduleRows as $s): ?><article class="panel schedule-card"><span class="stat-icon blue">◷</span><h2><?= e($s['name']) ?></h2><p><?= e(strtoupper($s['type'])) ?></p><strong><?= e(substr($s['work_start'],0,5)) ?>–<?= e(substr($s['break_start']??'',0,5)) ?> • <?= e(substr($s['break_end']??'',0,5)) ?>–<?= e(substr($s['work_end'],0,5)) ?></strong><small><?= round($s['weekly_minutes']/60,1) ?>h semanais • tolerância <?= (int)$s['tolerance_minutes'] ?> min</small></article><?php endforeach; ?></div>
    <dialog id="scheduleModal"><form method="post" action="/schedules/new"><div class="modal-head"><div><p class="eyebrow">CONFIGURAÇÃO</p><h2>Nova jornada</h2></div><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><div class="form-grid"><label class="span-2">Nome<input name="name" required></label><label>Tipo<select name="type"><option value="fixed">Fixa</option><option value="flexible">Flexível</option><option value="12x36">12×36</option><option value="custom">Personalizada</option></select></label><label>Carga semanal (minutos)<input type="number" name="weekly_minutes" value="2640" required></label><label>Entrada<input type="time" name="work_start" value="08:00" required></label><label>Início intervalo<input type="time" name="break_start" value="12:00"></label><label>Fim intervalo<input type="time" name="break_end" value="13:00"></label><label>Saída<input type="time" name="work_end" value="17:00" required></label><label>Tolerância (minutos)<input type="number" name="tolerance_minutes" value="10" min="0" required></label></div><div class="modal-actions"><button type="button" class="button ghost close-modal">Cancelar</button><button class="button primary">Salvar jornada</button></div></form></dialog>
  <?php elseif ($page==='companies'): ?>
    <article class="panel detail-card"><p class="eyebrow">EMPRESA ATIVA</p><h2><?= e($company['name']) ?></h2><div class="details"><div><span>CNPJ</span><strong><?= e($company['document']) ?></strong></div><div><span>Fuso horário</span><strong><?= e($company['timezone']) ?></strong></div><div><span>Status do agente</span><strong class="positive">Configurado</strong></div></div><button class="button primary" data-modal="companyModal">Editar empresa</button></article><dialog id="companyModal"><form method="post" action="/company/update"><div class="modal-head"><h2>Editar empresa</h2><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><label>Razão social / nome<input name="name" value="<?= e($company['name']) ?>" required></label><label>CNPJ<input name="document" value="<?= e($company['document']) ?>" required></label><label>Fuso horário<select name="timezone"><option value="America/Bahia" <?= $company['timezone']==='America/Bahia'?'selected':'' ?>>America/Bahia</option><option value="America/Sao_Paulo" <?= $company['timezone']==='America/Sao_Paulo'?'selected':'' ?>>America/São Paulo</option></select></label><div class="modal-actions"><button class="button primary">Salvar empresa</button></div></form></dialog>
  <?php elseif ($page==='users'): $userStmt=db()->prepare('SELECT id,name,email,role,active FROM users WHERE company_id=? ORDER BY name');$userStmt->execute([$companyId]);$userRows=$userStmt->fetchAll(); ?>
    <div class="page-actions"><div><h2>Acessos cadastrados</h2><p>Permissões por função</p></div><button class="button primary" data-modal="userModal">+ Novo usuário</button></div><article class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>Nome</th><th>E-mail</th><th>Perfil</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php foreach($userRows as $u): ?><tr><td><?= e($u['name']) ?></td><td><?= e($u['email']) ?></td><td><?= e(strtoupper($u['role'])) ?></td><td><span class="badge <?= $u['active']?'success':'warning' ?>"><?= $u['active']?'Ativo':'Inativo' ?></span></td><td><form method="post" action="/users/toggle" style="display:inline"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="user_id" value="<?= (int)$u['id'] ?>"><button class="button ghost"><?= $u['active']?'Desativar':'Ativar' ?></button></form> <button class="button ghost" data-modal="password<?= (int)$u['id'] ?>">Senha</button></td></tr><?php endforeach; ?></tbody></table></div></article><dialog id="userModal"><form method="post" action="/users/new"><div class="modal-head"><h2>Novo usuário</h2><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><label>Nome<input name="name" required></label><label>E-mail<input type="email" name="email" required></label><label>Perfil<select name="role"><option value="rh">RH</option><option value="gestor">Gestor</option><option value="auditor">Auditor</option><option value="admin">Administrador</option></select></label><label>Senha inicial<input type="password" name="password" minlength="8" required></label><div class="modal-actions"><button class="button primary">Criar usuário</button></div></form></dialog><?php foreach($userRows as $u): ?><dialog id="password<?= (int)$u['id'] ?>"><form method="post" action="/users/password"><div class="modal-head"><h2>Redefinir senha</h2><button type="button" class="close-modal">×</button></div><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="user_id" value="<?= (int)$u['id'] ?>"><label>Nova senha para <?= e($u['name']) ?><input type="password" name="password" minlength="8" required></label><div class="modal-actions"><button class="button primary">Salvar nova senha</button></div></form></dialog><?php endforeach; ?>
  <?php elseif ($page==='audit'): $logs=db()->prepare('SELECT * FROM audit_logs WHERE company_id=? ORDER BY created_at DESC LIMIT 50');$logs->execute([$companyId]); ?>
    <article class="panel table-panel"><div class="panel-head"><div><h2>Trilha de auditoria</h2><p>Ações registradas sem possibilidade de edição</p></div></div><div class="table-wrap"><table><thead><tr><th>Data</th><th>Ação</th><th>Entidade</th><th>Detalhes</th><th>IP</th></tr></thead><tbody><?php foreach($logs as $log): ?><tr><td><?= e(date('d/m/Y H:i',strtotime($log['created_at']))) ?></td><td><?= e($log['action']) ?></td><td><?= e($log['entity_type']) ?></td><td><?= e($log['details']) ?></td><td><?= e($log['ip_address']) ?></td></tr><?php endforeach; ?></tbody></table></div></article>
  <?php elseif ($page==='settings'): ?>
    <div class="settings-grid"><article class="panel"><h2>Regras de apuração</h2><form method="post" action="/settings/save"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><label>Tolerância diária (minutos)<input type="number" name="daily_tolerance_minutes" value="<?= (int)$settings['daily_tolerance_minutes'] ?>" min="0"></label><label>Hora extra em dia útil (%)<input type="number" name="overtime_weekday_percent" value="<?= e((string)$settings['overtime_weekday_percent']) ?>"></label><label>Hora extra em feriado (%)<input type="number" name="overtime_holiday_percent" value="<?= e((string)$settings['overtime_holiday_percent']) ?>"></label><label>Adicional noturno (%)<input type="number" name="night_additional_percent" value="<?= e((string)$settings['night_additional_percent']) ?>"></label><label>Duração da hora noturna (minutos)<input type="number" name="night_hour_minutes" value="<?= (int)$settings['night_hour_minutes'] ?>"></label><label>Dia de fechamento<input type="number" name="closing_day" value="<?= (int)$settings['closing_day'] ?>" min="1" max="31"></label><button class="button primary">Salvar regras</button></form></article><article class="panel"><h2>Agente comunicador</h2><p>Configure o agente instalado na rede do relógio para enviar marcações ao endpoint abaixo.</p><code>/api/agent/punches</code><span class="live"><i></i> Comunicação normal</span></article></div>
  <?php else: ?><article class="panel empty-state"><h2>Página não encontrada</h2><a class="button primary" href="/dashboard">Voltar ao painel</a></article><?php endif; ?>
  </section>
</main></div><script src="/assets/app.js"></script></body></html>
<?php
function render_punch_table(array $rows): void { ?>
<div class="table-wrap"><table><thead><tr><th>Colaborador</th><th>Data e hora</th><th>Setor</th><th>Origem</th><th>NSR</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?= e($row['name']) ?></strong><small>Matrícula <?= e($row['registration']) ?></small></td><td><?= e(date('d/m/Y • H:i:s',strtotime($row['punched_at']))) ?></td><td><?= e($row['department']) ?></td><td><span class="source-icon">◎</span> <?= e(ucfirst($row['source'])) ?></td><td><?= e($row['nsr'] ?: '—') ?></td><td><span class="badge success">Recebida</span></td></tr><?php endforeach; ?></tbody></table></div><?php }
?>
