<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Espelho de ponto • <?= e($timecardEmployee['name']) ?></title><link rel="stylesheet" href="/assets/app.css">
<style>.document{max-width:980px;margin:30px auto}.document-head{display:flex;justify-content:space-between;border-bottom:3px solid #173e67;padding-bottom:18px}.print-actions{display:flex;gap:10px;margin:20px 0}.accept-hash{overflow-wrap:anywhere}@media print{.print-actions,.accept-box{display:none}.document{margin:0}.panel{box-shadow:none}}</style></head>
<body><main class="document"><header class="document-head"><div><p class="eyebrow">ESPELHO DE PONTO ELETRÔNICO</p><h1><?= e($company['name']??'Empregador') ?></h1></div><div><strong><?= e(date('d/m/Y',strtotime($from))) ?> a <?= e(date('d/m/Y',strtotime($to))) ?></strong><p><?= e($timecardEmployee['name']) ?><br>Matrícula <?= e($timecardEmployee['registration']) ?></p></div></header>
<div class="print-actions"><button class="button primary" onclick="window.print()">Imprimir / Salvar PDF</button><a class="button ghost" href="/reports?from=<?= e($from) ?>&to=<?= e($to) ?>">Voltar</a></div>
<article class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>Data</th><th>Trabalhadas</th><th>Previstas</th><th>Extras</th><th>Atrasos</th><th>Noturnas</th><th>Ocorrências</th></tr></thead><tbody>
<?php foreach($timecardDays as $d): ?><tr><td><?= e(date('d/m/Y',strtotime($d['work_date']))) ?></td><td><?= ReportExporter::hours($d['worked_minutes']) ?></td><td><?= ReportExporter::hours($d['expected_minutes']) ?></td><td><?= ReportExporter::hours($d['overtime_minutes']) ?></td><td><?= ReportExporter::hours($d['delay_minutes']) ?></td><td><?= ReportExporter::hours($d['night_minutes']) ?></td><td><?= e(implode(', ',json_decode($d['issues']?:'[]',true))) ?></td></tr><?php endforeach; ?>
<?php if(!$timecardDays): ?><tr><td colspan="7">Nenhuma apuração encontrada. Processe o período antes de gerar o espelho.</td></tr><?php endif; ?>
</tbody></table></div></article>
<article class="panel accept-box"><h2>Aceite eletrônico</h2>
<?php if($timecardAcceptance): ?><p><strong>Aceite registrado por <?= e($timecardAcceptance['accepted_name']) ?></strong><br>Data: <?= e(date('d/m/Y H:i',strtotime($timecardAcceptance['accepted_at']))) ?><br>Código de integridade: <code class="accept-hash"><?= e($timecardAcceptance['acceptance_hash']) ?></code></p>
<?php else: ?><p>Confirmo que conferi as informações apresentadas neste espelho.</p><form method="post" action="/timecard/accept"><input type="hidden" name="_token" value="<?= csrf_token() ?>"><input type="hidden" name="employee_id" value="<?= (int)$timecardEmployee['id'] ?>"><input type="hidden" name="from" value="<?= e($from) ?>"><input type="hidden" name="to" value="<?= e($to) ?>"><label>Nome completo<input name="accepted_name" required></label><button class="button primary">Registrar aceite</button></form><?php endif; ?>
</article></main></body></html>
